name: neom_instruments
description: Instruments and Genres for Cyberneom.
version: 1.2.1
homepage: https://github.com/Cyberneom/neom_instruments
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
